workflow: GitHubFlow/v1

mode: ManualDeployment

major-version-bump-message: '^(.*!|.*BREAKING CHANGE:.*)$'
minor-version-bump-message: '^feat(\(.*\))?:'
patch-version-bump-message: '^(fix|perf)(\(.*\))?:'

branches:
  main:
    label: 'dev'
    mode: ManualDeployment
    increment: Patch

  release:
    regex: '^release$'
    label: ''
    mode: ManualDeployment
    increment: Patch
    prevent-increment:
      when-current-commit-tagged: true

  feature:
    label: '{BranchName}'
    mode: ManualDeployment
    increment: Inherit

  pull-request:
    label: PullRequest{Number}
    mode: ManualDeployment
    increment: Inherit

ignore:
  sha: []
