//! 파일 출력: AssemblyInfo, 프로젝트 파일, Wix.
//!
//! 원본 `GitVersion.Output/AssemblyInfo/*`, `WixUpdater/*` 대응.

use super::variables::VersionVariables;
use anyhow::{Context, Result};
use regex::Regex;
use std::path::{Path, PathBuf};

/// AssemblyInfo 생성 시 템플릿 헤더(원본과 동일).
const ASSEMBLY_HEADER: &str = "\
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------
";

/// 재귀적으로 주어진 파일명들과 일치하는 파일을 찾는다.
fn find_recursive(root: &Path, matches: impl Fn(&Path) -> bool) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else { continue };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                // .git 등 숨김 디렉터리는 건너뛴다.
                if path.file_name().map(|n| n.to_string_lossy().starts_with('.')).unwrap_or(false) {
                    continue;
                }
                stack.push(path);
            } else if matches(&path) {
                out.push(path);
            }
        }
    }
    out.sort();
    out
}

/// AssemblyInfo 파일들을 갱신(없으면 ensure 시 생성).
///
/// `files` 가 비어 있으면 작업 디렉터리에서 AssemblyInfo.{cs,vb,fs} 를 재귀 탐색.
pub fn update_assembly_info(
    vars: &VersionVariables,
    work_dir: &Path,
    files: &[String],
    ensure: bool,
) -> Result<Vec<PathBuf>> {
    let targets: Vec<PathBuf> = if files.is_empty() {
        find_recursive(work_dir, |p| {
            let name = p.file_name().map(|n| n.to_string_lossy().to_lowercase()).unwrap_or_default();
            matches!(name.as_str(), "assemblyinfo.cs" | "assemblyinfo.vb" | "assemblyinfo.fs")
        })
    } else {
        files.iter().map(|f| work_dir.join(f)).collect()
    };

    let mut updated = Vec::new();
    for path in targets {
        if path.exists() {
            let content = std::fs::read_to_string(&path)
                .with_context(|| format!("읽기 실패: {}", path.display()))?;
            let new = replace_assembly_attributes(&content, vars);
            std::fs::write(&path, new)?;
            updated.push(path);
        } else if ensure {
            let content = create_assembly_info(&path, vars);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent).ok();
            }
            std::fs::write(&path, content)?;
            updated.push(path);
        }
    }
    Ok(updated)
}

/// 기존 AssemblyInfo 의 세 속성 값을 정규식으로 치환.
fn replace_assembly_attributes(content: &str, vars: &VersionVariables) -> String {
    let replace_attr = |text: &str, attr: &str, value: &str| -> String {
        // AssemblyVersion("...") / <Assembly: AssemblyVersion("...")> 모두 매칭.
        let re = Regex::new(&format!(r#"({attr}\s*\(\s*")[^"]*("\s*\))"#)).unwrap();
        re.replace_all(text, format!("${{1}}{value}${{2}}").as_str()).into_owned()
    };
    let mut out = content.to_string();
    out = replace_attr(&out, "AssemblyFileVersion", &vars.assembly_sem_file_ver);
    out = replace_attr(&out, "AssemblyInformationalVersion", &vars.informational_version);
    out = replace_attr(&out, "AssemblyVersion", &vars.assembly_sem_ver);
    out
}

/// 새 AssemblyInfo 파일 내용 생성(확장자별 문법).
fn create_assembly_info(path: &Path, vars: &VersionVariables) -> String {
    let ext = path.extension().map(|e| e.to_string_lossy().to_lowercase()).unwrap_or_default();
    let (fv, av, iv) =
        (&vars.assembly_sem_file_ver, &vars.assembly_sem_ver, &vars.informational_version);
    match ext.as_str() {
        "vb" => format!(
            "{ASSEMBLY_HEADER}\nImports System.Reflection\n\n\
             <Assembly: AssemblyFileVersion(\"{fv}\")>\n\
             <Assembly: AssemblyVersion(\"{av}\")>\n\
             <Assembly: AssemblyInformationalVersion(\"{iv}\")>\n"
        ),
        "fs" => format!(
            "{ASSEMBLY_HEADER}\nnamespace AssemblyInfo\n\nopen System.Reflection\n\n\
             [<assembly: AssemblyFileVersion(\"{fv}\")>]\n\
             [<assembly: AssemblyVersion(\"{av}\")>]\n\
             [<assembly: AssemblyInformationalVersion(\"{iv}\")>]\n\
             do ()\n"
        ),
        _ => format!(
            "{ASSEMBLY_HEADER}\nusing System.Reflection;\n\n\
             [assembly: AssemblyFileVersion(\"{fv}\")]\n\
             [assembly: AssemblyVersion(\"{av}\")]\n\
             [assembly: AssemblyInformationalVersion(\"{iv}\")]\n"
        ),
    }
}

/// .csproj/.vbproj/.fsproj 의 버전 요소를 갱신.
pub fn update_project_files(
    vars: &VersionVariables,
    work_dir: &Path,
    files: &[String],
) -> Result<Vec<PathBuf>> {
    let targets: Vec<PathBuf> = if files.is_empty() {
        find_recursive(work_dir, |p| {
            let ext = p.extension().map(|e| e.to_string_lossy().to_lowercase()).unwrap_or_default();
            matches!(ext.as_str(), "csproj" | "vbproj" | "fsproj")
        })
    } else {
        files.iter().map(|f| work_dir.join(f)).collect()
    };

    let mut updated = Vec::new();
    for path in targets {
        if !path.exists() {
            continue;
        }
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("읽기 실패: {}", path.display()))?;
        let new = replace_project_elements(&content, vars);
        std::fs::write(&path, new)?;
        updated.push(path);
    }
    Ok(updated)
}

/// 프로젝트 파일의 XML 요소 텍스트를 치환(존재하는 요소만).
fn replace_project_elements(content: &str, vars: &VersionVariables) -> String {
    let replace_elem = |text: &str, elem: &str, value: &str| -> String {
        let re = Regex::new(&format!(r"(<{elem}>)[^<]*(</{elem}>)")).unwrap();
        re.replace_all(text, format!("${{1}}{value}${{2}}").as_str()).into_owned()
    };
    let mut out = content.to_string();
    out = replace_elem(&out, "AssemblyVersion", &vars.assembly_sem_ver);
    out = replace_elem(&out, "FileVersion", &vars.assembly_sem_file_ver);
    out = replace_elem(&out, "InformationalVersion", &vars.informational_version);
    out = replace_elem(&out, "Version", &vars.sem_ver);
    out
}

/// Wix 버전 파일(GitVersion_WixVersion.wxi) 생성.
pub fn write_wix(vars: &VersionVariables, work_dir: &Path) -> Result<PathBuf> {
    let mut s = String::new();
    s.push('\u{feff}'); // UTF-8 BOM
    s.push_str("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
    s.push_str("<Include xmlns=\"http://schemas.microsoft.com/wix/2006/wi\">\n");
    for (key, value) in vars.to_map() {
        s.push_str(&format!("  <?define {key}=\"{value}\"?>\n"));
    }
    s.push_str("</Include>");
    let path = work_dir.join("GitVersion_WixVersion.wxi");
    std::fs::write(&path, s)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn vars() -> VersionVariables {
        VersionVariables {
            assembly_sem_ver: "1.0.1.0".into(),
            assembly_sem_file_ver: "1.0.1.0".into(),
            informational_version: "1.0.1-1+Branch.main".into(),
            sem_ver: "1.0.1-1".into(),
            ..Default::default()
        }
    }

    #[test]
    fn assembly_attribute_replacement() {
        let src = "[assembly: AssemblyVersion(\"0.0.0.0\")]\n\
                   [assembly: AssemblyFileVersion(\"0.0.0.0\")]\n\
                   [assembly: AssemblyInformationalVersion(\"0.0.0.0\")]\n";
        let out = replace_assembly_attributes(src, &vars());
        assert!(out.contains("AssemblyVersion(\"1.0.1.0\")"));
        assert!(out.contains("AssemblyFileVersion(\"1.0.1.0\")"));
        assert!(out.contains("AssemblyInformationalVersion(\"1.0.1-1+Branch.main\")"));
    }

    #[test]
    fn project_element_replacement() {
        let src = "<Version>0.0.0</Version><AssemblyVersion>0.0.0.0</AssemblyVersion>";
        let out = replace_project_elements(src, &vars());
        assert!(out.contains("<Version>1.0.1-1</Version>"));
        assert!(out.contains("<AssemblyVersion>1.0.1.0</AssemblyVersion>"));
    }

    #[test]
    fn create_cs_assembly_info() {
        let out = create_assembly_info(Path::new("AssemblyInfo.cs"), &vars());
        assert!(out.contains("using System.Reflection;"));
        assert!(out.contains("[assembly: AssemblyFileVersion(\"1.0.1.0\")]"));
        assert!(out.starts_with("//---"));
    }
}
